spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080